version: "3.9"

volumes:
  minio:
  postgres:

services:

  minio:
    image: "docker.io/bitnami/minio:2023"
    container_name: "back_template_minio"
    restart: "always"
    shm_size: "512m"
    labels:
      job: "minio-db"
    environment:
      MINIO_ROOT_USER: "test_svc"
      MINIO_ROOT_PASSWORD: "test_pass"
    ports:
      - "${BACK_TEMPLATE_MINIO_ADDR_HTTP_PORT:-0}:9000"
      - "${BACK_TEMPLATE_MINIO_ADDR_ADMIN_PORT:-0}:9001"
    volumes:
      - "minio:/data/"

  postgres:
    image: postgres:16.1
    container_name: "back_template_postgres"
    restart: unless-stopped
    volumes:
      - "postgres:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: "user_db"
      POSTGRES_USER: "user_svc"
      POSTGRES_PASSWORD: "user_pass"
    ports:
      - "${BACK_TEMPLATE_POSTGRES_ADDR_PORT:-0}:5432"

  backend:
    build:
      context: .
      dockerfile: ./cmd/back/docker/Dockerfile
    container_name: "back_template_backend"
    restart: always
    labels:
      service: "backend"
    command: [
      "-cfg=/config.yml",
      "-log_level=debug",
    ]
    volumes:
      - "${BACK_SVC_CONFIG}:/config.yml"
    ports:
      - "${BACK_SVC_GRPC_PORT}:8080" # gRPC
      - "${BACK_SVC_METRIC_PORT}:8081" # metric
      - "${BACK_SVC_GRPC_GW_PORT}:8082" # gRPC-Gateway
      - "${BACK_SVC_GRPC_FILES_PORT}:8083" # file srv

  promtail:
    image: "grafana/promtail:3.3.1"
    container_name: "back_template_promtail"
    restart: "always"
    volumes:
      - "./configs/promtail/promtail.yml:/etc/promtail/docker-config.yml"
      - "/var/lib/docker/containers:/var/lib/docker/containers:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: [
      "-config.file=/etc/promtail/docker-config.yml",
      "-log.format=json",
    ]

  loki:
    image: "grafana/loki:3.3.1"
    ports:
      - "3100:3100"
    volumes:
      - "./configs/promtail/promtail.yml:/etc/promtail/docker-config.yml"
    command: [
      "-config.file=/etc/loki/local-config.yml"
    ]

  grafana:
    image: "grafana/grafana:10.2.1"
    ports:
      - "3000:3000"
    volumes:
      - "./configs/grafana/provisioning/:/etc/grafana/provisioning/"
      - "./configs/grafana/config.ini:/local/grafana.ini"
    environment:
      - "GF_PATHS_CONFIG=/local/grafana.ini"
      - "GF_SERVER_SERVE_FROM_SUB_PATH=true"
      - "GF_AUTH_ANONYMOUS_ENABLED=true"
      - "GF_AUTH_ANONYMOUS_ORG_ROLE=Admin"
      - "GF_AUTH_DISABLE_LOGIN_FORM=true"



