#!/bin/sh

# Database settings.
export BACK_TEMPLATE_POSTGRES_ADDR_PORT="5432"

# File storage settings.
export BACK_TEMPLATE_MINIO_NODE1_ADDR_HTTP_PORT="9100"
export BACK_TEMPLATE_MINIO_NODE1_ADDR_ADMIN_PORT="9101"

# back svc
export BACK_SVC_CONFIG="./cmd/back/config.yml"
export BACK_SVC_GRPC_PORT=10000
export BACK_SVC_METRIC_PORT=10001
export BACK_SVC_GRPC_GW_PORT=10002
export BACK_SVC_GRPC_FILES_PORT=10003
