server:
  host: "0.0.0.0"
  port:
    grpc: 8080
    metric: 8081
db:
  migrate_dir: "migrate"
  driver: "postgres"
  cockroach:
    user: "mail_svc"
    password: "mail_pass"
    host: "cockroach-node3"
    port: 26257
    database: "mail_db"
    parameters:
      application_name: "mail_service"
      mode: "require"
queue:
  urls: [
    "nats://nats-node1:4222",
    "nats://nats-node2:4222",
    "nats://nats-node3:4222",
  ]
  username: "mail_svc"
  password: "super_duper_secret_key"
mailer:
  gmail:
    sender_name: "mailer_svc"
    sender_email_address: "mailer_svc@gmail.com"
    sender_email_password: "mailerpassfromgmail"